# Generated by Django 6.0.2 on 2026-03-03 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_pasaport_no', models.CharField(max_length=50, unique=True)),
                ('kimlik_tipi', models.CharField(choices=[('TC', 'T.C. Kimlik Kartı'), ('YABANCI', 'Yab. Kimlik Kartı'), ('PASAPORT', 'Pasaport'), ('ID_KART', 'ID Kart')], max_length=20)),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('baba_adi', models.CharField(blank=True, max_length=100, null=True)),
                ('anne_adi', models.CharField(blank=True, max_length=100, null=True)),
                ('dogum_yeri', models.CharField(blank=True, max_length=100, null=True)),
                ('dogum_tarihi', models.DateField(blank=True, null=True)),
                ('telefon1', models.CharField(max_length=20)),
                ('telefon2', models.CharField(blank=True, max_length=20, null=True)),
                ('eposta', models.EmailField(max_length=254)),
                ('turkiye_adresi', models.TextField(blank=True, null=True)),
                ('ulke_adresi', models.TextField(blank=True, null=True)),
                ('ulke_telefonu', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IndirimTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Seviye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SinavTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150)),
                ('egitim_sekli', models.CharField(choices=[('YUZYUZE', 'Yüz Yüze'), ('CEVRIMICI', 'Çevrim İçi')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Uyruk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Basvuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egitim_sekli', models.CharField(choices=[('YUZYUZE', 'Yüz Yüze'), ('CEVRIMICI', 'Çevrim İçi')], max_length=20)),
                ('indirim_kodu', models.CharField(blank=True, max_length=50, null=True)),
                ('indirim_belgesi', models.FileField(blank=True, null=True, upload_to='indirim_belgeleri/')),
                ('kimlik_dosyasi', models.FileField(blank=True, null=True, upload_to='kimlik_dosyalari/')),
                ('kayit_bilgi_notu', models.TextField(blank=True, null=True)),
                ('vize_turu', models.CharField(blank=True, max_length=100, null=True)),
                ('vize_baslangic', models.DateField(blank=True, null=True)),
                ('vize_bitis', models.DateField(blank=True, null=True)),
                ('basvuru_tarihi', models.DateTimeField(auto_now_add=True)),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], default='BEKLIYOR', max_length=20)),
                ('aday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basvurular', to='api.aday')),
                ('dil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dil')),
                ('indirim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.indirimturu')),
                ('sube', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sube')),
            ],
        ),
        migrations.AddField(
            model_name='aday',
            name='uyruk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.uyruk'),
        ),
        migrations.CreateModel(
            name='KursBasvurusu',
            fields=[
                ('basvuru_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basvuru')),
                ('seviye', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.seviye')),
            ],
            bases=('api.basvuru',),
        ),
        migrations.CreateModel(
            name='SinavBasvurusu',
            fields=[
                ('basvuru_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basvuru')),
                ('sinav_turu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sinavturu')),
            ],
            bases=('api.basvuru',),
        ),
    ]
