# Generated by Django 6.0.2 on 2026-03-17 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kursbasvurusu',
            name='basvuru_ptr',
        ),
        migrations.RemoveField(
            model_name='sinavbasvurusu',
            name='basvuru_ptr',
        ),
        migrations.RemoveField(
            model_name='kursbasvurusu',
            name='seviye',
        ),
        migrations.RemoveField(
            model_name='sinavbasvurusu',
            name='sinav_turu',
        ),
        migrations.RemoveField(
            model_name='aday',
            name='turkiye_adresi',
        ),
        migrations.RemoveField(
            model_name='aday',
            name='ulke_adresi',
        ),
        migrations.RemoveField(
            model_name='aday',
            name='ulke_telefonu',
        ),
        migrations.AlterField(
            model_name='aday',
            name='kimlik_tipi',
            field=models.CharField(blank=True, choices=[('TC', 'T.C. Kimlik Kartı'), ('YABANCI', 'Yab. Kimlik Kartı'), ('PASAPORT', 'Pasaport'), ('ID_KART', 'ID Kart')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='KursCevrimIci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimlik_dosyasi', models.FileField(blank=True, null=True, upload_to='kimlik_dosyalari/')),
                ('kayit_bilgi_notu', models.TextField(blank=True, null=True)),
                ('basvuru_tarihi', models.DateTimeField(auto_now_add=True)),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], default='BEKLIYOR', max_length=20)),
                ('indirim_kodu', models.CharField(blank=True, max_length=50, null=True)),
                ('indirim_belgesi', models.FileField(blank=True, null=True, upload_to='indirim_belgeleri/')),
                ('vize_turu', models.CharField(blank=True, max_length=100, null=True)),
                ('kayit_turu', models.CharField(blank=True, max_length=100, null=True)),
                ('vize_baslangic', models.DateField(blank=True, null=True)),
                ('vize_bitis', models.DateField(blank=True, null=True)),
                ('turkiye_adresi', models.TextField(blank=True, null=True)),
                ('ulke_adresi', models.TextField(blank=True, null=True)),
                ('ulke_telefonu', models.CharField(blank=True, max_length=20, null=True)),
                ('aday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_basvurulari', to='api.aday')),
                ('dil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dil')),
                ('indirim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.indirimturu')),
                ('seviye', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.seviye')),
                ('sube', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sube')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KursYuzYuze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimlik_dosyasi', models.FileField(blank=True, null=True, upload_to='kimlik_dosyalari/')),
                ('kayit_bilgi_notu', models.TextField(blank=True, null=True)),
                ('basvuru_tarihi', models.DateTimeField(auto_now_add=True)),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], default='BEKLIYOR', max_length=20)),
                ('indirim_kodu', models.CharField(blank=True, max_length=50, null=True)),
                ('indirim_belgesi', models.FileField(blank=True, null=True, upload_to='indirim_belgeleri/')),
                ('aday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_basvurulari', to='api.aday')),
                ('dil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dil')),
                ('indirim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.indirimturu')),
                ('seviye', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.seviye')),
                ('sube', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sube')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SinavCevrimIci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimlik_dosyasi', models.FileField(blank=True, null=True, upload_to='kimlik_dosyalari/')),
                ('kayit_bilgi_notu', models.TextField(blank=True, null=True)),
                ('basvuru_tarihi', models.DateTimeField(auto_now_add=True)),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], default='BEKLIYOR', max_length=20)),
                ('sinav_turu', models.CharField(blank=True, max_length=150, null=True)),
                ('vize_turu', models.CharField(blank=True, max_length=100, null=True)),
                ('vize_baslangic', models.DateField(blank=True, null=True)),
                ('vize_bitis', models.DateField(blank=True, null=True)),
                ('turkiye_adresi', models.TextField(blank=True, null=True)),
                ('ulke_adresi', models.TextField(blank=True, null=True)),
                ('ulke_telefonu', models.CharField(blank=True, max_length=20, null=True)),
                ('aday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_basvurulari', to='api.aday')),
                ('dil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dil')),
                ('sube', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sube')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SinavYuzYuze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimlik_dosyasi', models.FileField(blank=True, null=True, upload_to='kimlik_dosyalari/')),
                ('kayit_bilgi_notu', models.TextField(blank=True, null=True)),
                ('basvuru_tarihi', models.DateTimeField(auto_now_add=True)),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], default='BEKLIYOR', max_length=20)),
                ('sinav_turu', models.CharField(blank=True, max_length=150, null=True)),
                ('aday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_basvurulari', to='api.aday')),
                ('dil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dil')),
                ('sube', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sube')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Basvuru',
        ),
        migrations.DeleteModel(
            name='KursBasvurusu',
        ),
        migrations.DeleteModel(
            name='SinavBasvurusu',
        ),
    ]
