# Generated by Django 6.0.2 on 2026-03-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_kursbasvurusu_basvuru_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurscevrimici',
            name='onay_bilgiler_dogru',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kurscevrimici',
            name='onay_fatura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kurscevrimici',
            name='onay_kursiyerlik',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kurscevrimici',
            name='onay_sorumluluk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kursyuzyuze',
            name='onay_bilgiler_dogru',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kursyuzyuze',
            name='onay_fatura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kursyuzyuze',
            name='onay_kursiyerlik',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kursyuzyuze',
            name='onay_sorumluluk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sinavcevrimici',
            name='onay_bilgiler_dogru',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sinavcevrimici',
            name='onay_fatura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sinavcevrimici',
            name='onay_kursiyerlik',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sinavcevrimici',
            name='onay_sorumluluk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sinavyuzyuze',
            name='onay_bilgiler_dogru',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sinavyuzyuze',
            name='onay_fatura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sinavyuzyuze',
            name='onay_kursiyerlik',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sinavyuzyuze',
            name='onay_sorumluluk',
            field=models.BooleanField(default=False),
        ),
    ]
