# Generated by Django 6.0.2 on 2026-03-23 09:06

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_kurscevrimici_onay_bilgiler_dogru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurscevrimici',
            name='indirim_belgesi',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_indirim_path),
        ),
        migrations.AlterField(
            model_name='kurscevrimici',
            name='kimlik_dosyasi',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_kimlik_path),
        ),
        migrations.AlterField(
            model_name='kursyuzyuze',
            name='indirim_belgesi',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_indirim_path),
        ),
        migrations.AlterField(
            model_name='kursyuzyuze',
            name='kimlik_dosyasi',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_kimlik_path),
        ),
        migrations.AlterField(
            model_name='sinavcevrimici',
            name='kimlik_dosyasi',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_kimlik_path),
        ),
        migrations.AlterField(
            model_name='sinavyuzyuze',
            name='kimlik_dosyasi',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_kimlik_path),
        ),
    ]
