# Generated by Django 6.0.2 on 2026-05-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='application_type',
            field=models.CharField(blank=True, choices=[('KURS', 'Kurs'), ('SINAV', 'Sınav')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='education_mode',
            field=models.CharField(blank=True, choices=[('YUZ_YUZE', 'Yüz Yüze'), ('CEVRIM_ICI', 'Çevrim İçi')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='identity_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='identity_type',
            field=models.CharField(blank=True, choices=[('TC', 'TC Kimlik'), ('PASSPORT', 'Pasaport'), ('OTHER', 'Diğer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
