# Generated by Django 6.0.2 on 2026-05-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_application_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='department',
            field=models.CharField(choices=[('turkce', 'Türkçe Öğretimi (TÖMER)'), ('ingilizce', 'İngilizce Hazırlık Koordinatörlüğü'), ('almanca', 'Almanca Hazırlık Koordinatörlüğü'), ('diger', 'Diğer')], max_length=50),
        ),
    ]
