# Generated by Django 6.0.2 on 2026-05-23 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_alter_kurscevrimici_indirim_belgesi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sınav Başlığı')),
                ('passing_score', models.IntegerField(default=70, verbose_name='Geçme Barajı (%)')),
                ('total_questions', models.IntegerField(default=20, verbose_name='Toplam Soru Sayısı')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sinav_kurali', to='api.seviye', verbose_name='Seviye')),
            ],
            options={
                'verbose_name': 'Seviye Tespit Sınavı',
                'verbose_name_plural': 'Seviye Tespit Sınavları',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Soru Metni')),
                ('option_a', models.CharField(max_length=500, verbose_name='A Şıkkı')),
                ('option_b', models.CharField(max_length=500, verbose_name='B Şıkkı')),
                ('option_c', models.CharField(max_length=500, verbose_name='C Şıkkı')),
                ('option_d', models.CharField(max_length=500, verbose_name='D Şıkkı')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Doğru Cevap')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorular', to='api.seviye', verbose_name='Seviye')),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
            },
        ),
        migrations.CreateModel(
            name='StudentExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Alınan Puan')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Geçti mi?')),
                ('exam_date', models.DateTimeField(auto_now_add=True, verbose_name='Sınav Tarihi')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sonuclar', to='exams.levelexam', verbose_name='Sınav')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinav_sonuclari', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Sınav Sonucu',
                'verbose_name_plural': 'Sınav Sonuçları',
                'ordering': ['-exam_date'],
            },
        ),
    ]
