# Generated by Django 6.0.2 on 2026-05-24 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_kurscevrimici_indirim_belgesi_and_more'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='levelexam',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='Süre (dakika)'),
        ),
        migrations.AddField(
            model_name='levelexam',
            name='is_adaptive',
            field=models.BooleanField(default=True, verbose_name='Adaptive mi?'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_reading',
            field=models.BooleanField(default=False, verbose_name='Reading sorusu mu?'),
        ),
        migrations.AddField(
            model_name='question',
            name='reading_text',
            field=models.TextField(blank=True, help_text='Eğer Reading sorusuysa uzun paragraf metnini buraya yazın.', null=True, verbose_name='Reading Paragraf Metni'),
        ),
        migrations.AlterField(
            model_name='levelexam',
            name='level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sinav_kurali', to='api.seviye', verbose_name='Seviye'),
        ),
        migrations.CreateModel(
            name='StudentExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_counter', models.IntegerField(default=0, verbose_name='Sorulan Soru Sayısı')),
                ('correct_counter', models.IntegerField(default=0, verbose_name='Doğru Cevap Sayısı')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlandı mı?')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç Zamanı')),
                ('current_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_sessions', to='api.seviye', verbose_name='Anlık Seviye')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exams.levelexam', verbose_name='Sınav')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Sınav Oturumu',
                'verbose_name_plural': 'Sınav Oturumları',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAdaptiveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=1, verbose_name='Seçilen Şık')),
                ('is_correct', models.BooleanField(verbose_name='Doğru mu?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_answers', to='exams.question', verbose_name='Soru')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.studentexamsession', verbose_name='Oturum')),
            ],
            options={
                'verbose_name': 'Adaptive Cevap',
                'verbose_name_plural': 'Adaptive Cevaplar',
            },
        ),
    ]
