# Generated by Django 6.0.2 on 2026-05-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_levelexam_duration_levelexam_is_adaptive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelexam',
            options={'verbose_name': 'Seviye Tespit Sinavi', 'verbose_name_plural': 'Seviye Tespit Sinavlari'},
        ),
        migrations.AddField(
            model_name='levelexam',
            name='exam_type',
            field=models.CharField(choices=[('PLACEMENT', 'Seviye Tespit Sinavi'), ('GRAMMAR', 'Ana Test (Gramer)'), ('LISTENING', 'Dinleme Sinavi'), ('READING', 'Okuma Sinavi'), ('WRITING', 'Yazma Sinavi')], default='PLACEMENT', max_length=50, verbose_name='Sinav Turu'),
        ),
        migrations.AddField(
            model_name='levelexam',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='exams', to='exams.question', verbose_name='Sinav Sorulari'),
        ),
        migrations.AlterField(
            model_name='levelexam',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='Sure (dakika)'),
        ),
        migrations.AlterField(
            model_name='levelexam',
            name='passing_score',
            field=models.IntegerField(default=70, verbose_name='Gecme Baraji (%)'),
        ),
        migrations.AlterField(
            model_name='levelexam',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sinav Basligi'),
        ),
        migrations.AlterField(
            model_name='levelexam',
            name='total_questions',
            field=models.IntegerField(default=20, verbose_name='Toplam Soru Sayisi'),
        ),
    ]
