# Generated by Django 6.0.2 on 2026-05-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_levelexam_options_levelexam_exam_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='listening_audios/', verbose_name='Ses Dosyasi (MP3)'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('GRAMMAR', 'Gramer'), ('READING', 'Okuma'), ('LISTENING', 'Dinleme'), ('WRITING', 'Yazma'), ('SPEAKING', 'Konusma')], default='GRAMMAR', max_length=20, verbose_name='Soru Tipi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True, verbose_name='Dogru Cevap'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='A Sikki'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='B Sikki'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='C Sikki'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='D Sikki'),
        ),
        migrations.AlterField(
            model_name='question',
            name='reading_text',
            field=models.TextField(blank=True, null=True, verbose_name='Reading Paragraf Metni'),
        ),
    ]
