# Generated by Django 6.0.2 on 2026-05-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_question_audio_file_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('GRAMMAR', 'Gramer'), ('READING', 'Okuma'), ('LISTENING', 'Dinleme'), ('WRITING', 'Yazma')], default='GRAMMAR', max_length=20, verbose_name='Soru Tipi'),
        ),
    ]
