# Generated by Django 6.0.2 on 2026-05-25 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_kurscevrimici_indirim_belgesi_and_more'),
        ('exams', '0005_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelexam',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.seviye', verbose_name='Seviye'),
        ),
    ]
