# Generated by Django 6.0.2 on 2026-05-26 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_levelexam_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('BASLATILDI', 'Başlatıldı'), ('TAMAMLANDI', 'Tamamlandı')], default='BEKLIYOR', max_length=20, verbose_name='Durum')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Atanma Tarihi')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.levelexam', verbose_name='Sınav')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Sınav Ataması',
                'verbose_name_plural': 'Sınav Atamaları',
                'ordering': ['-assigned_at'],
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
