# Generated by Django 6.0.2 on 2026-06-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_studentexamassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelexam',
            name='language',
            field=models.CharField(choices=[('turkce', 'Türkçe'), ('ingilizce', 'İngilizce'), ('almanca', 'Almanca')], default='turkce', max_length=50, verbose_name='Dil'),
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('turkce', 'Türkçe'), ('ingilizce', 'İngilizce'), ('almanca', 'Almanca')], default='turkce', max_length=50, verbose_name='Dil'),
        ),
    ]
