# Generated by Django 6.0.2 on 2026-06-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_levelexam_language_question_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelexam',
            name='is_adaptive',
        ),
    ]
