# Generated by Django 6.0.2 on 2026-06-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_remove_levelexam_is_adaptive'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelexam',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Yayında mı?'),
        ),
    ]
