# Generated by Django 6.0.2 on 2026-06-07 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_levelexam_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField(verbose_name='Öğrenci Metni')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Eğitmen Puanı')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to='exams.levelexam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to='exams.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yazma Sınavı Gönderimi',
                'verbose_name_plural': 'Yazma Sınav Gönderimleri',
            },
        ),
    ]
