# Generated by Django 6.0.2 on 2026-06-08 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_studentwritingsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True, verbose_name='Seçilen Şık')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='Yazı/Metin Cevabı')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Doğru mu?')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Eğitmen Notu')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='exams.levelexam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='exams.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Öğrenci Cevabı (Statik)',
                'verbose_name_plural': 'Öğrenci Cevapları (Statik)',
            },
        ),
    ]
