# Generated by Django 6.0.2 on 2026-06-28 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_studentanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentexamassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentexamassignment',
            name='achieved_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Alınan Puan'),
        ),
        migrations.AddField(
            model_name='studentexamassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exams_given', to=settings.AUTH_USER_MODEL, verbose_name='Atamayı Yapan Eğitmen'),
        ),
        migrations.AlterField(
            model_name='studentexamassignment',
            name='status',
            field=models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('BASLATILDI', 'Başlatıldı'), ('TAMAMLANDI', 'Tamamlandı'), ('BASARISIZ', 'Başarısız')], default='BEKLIYOR', max_length=20, verbose_name='Durum'),
        ),
    ]
