# Generated by Django 6.0.2 on 2026-05-31 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructortask',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file_size',
            field=models.CharField(blank=True, default='', help_text='Örn: 2.4 MB', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='level',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], default='A1', max_length=10),
        ),
        migrations.AlterField(
            model_name='instructortask',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
