# Generated by Django 6.0.2 on 2026-05-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_coursematerial_uploaded_by_instructortask_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='supplementary_file',
            field=models.FileField(blank=True, null=True, upload_to='materials/extras/'),
        ),
        migrations.AddField(
            model_name='instructortask',
            name='supplementary_file',
            field=models.FileField(blank=True, null=True, upload_to='materials/extras/'),
        ),
    ]
